USE Pomodoro; 

IF OBJECT_ID('Tasks') IS NULL
BEGIN
	CREATE TABLE Tasks (
		Id INT IDENTITY(1,1) NOT NULL,
		Title VARCHAR(50) NOT NULL,
		ActualQuantity TINYINT DEFAULT 1,
		EstimatedQuantity TINYINT DEFAULT 1,
		Note VARCHAR(150) NOT NULL,
		ProjectId INT,
		CONSTRAINT PK_Tasks_Id
			PRIMARY KEY (Id),
		CONSTRAINT FK_Tasks_Projects FOREIGN KEY (ProjectId)
			REFERENCES Projects(Id)
	);
END
